qlib_init:
    provider_uri: "~/.qlib/qlib_data/cn_data"
    region: cn
market: &market csi300
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2020-08-01
    fit_start_time: 2008-01-01
    fit_end_time: 2014-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: ["RESI5", "WVMA5", "RSQR5", "KLEN", "RSQR10", "CORR5", "CORD5", "CORR10",
                            "ROC60", "RESI10", "VSTD5", "RSQR60", "CORR60", "WVMA60", "STD5",
                            "RSQR20", "CORD60", "CORD10", "CORR20", "KLOW"
                        ]
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"]

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2017-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: AutoformerModel
        module_path: qlib.contrib.model.pytorch_autoformer
        kwargs:
            seed: 0       # Random seed, no need to adjust
            n_jobs: 20    # Number of parallel jobs, no need to adjust
            d_model: 16   # Adjustable range [16, 32, 64, 128], model feature dimension, directly corresponds to the total number of model parameters. It's not advisable to set too high to prevent high memory usage, slow training, and over-fitting. Bigger model size doesn't always mean better performance.
            d_ff: 64      # Adjustable range [32, 64, 128], dimension of the feedforward layer
            num_layers: 2 # Adjustable range [1, 2, 3, 4], number of network layers, also corresponds to the model's parameter count, similar to d_model
            token_size: 3 # Adjustable range [3, 5, 7, 9, 11], token size, used for data segmentation
            dropout: 0.2  # Adjustable range 0-1 as a float, dropout rate, higher values can mitigate over-fitting but generally shouldn't exceed 0.5
            lr: 0.0001    # Adjustable range [0.00005, 0.0001, 0.0002, 0.0005, 0.001], learning rate, very important
            early_stop: 5 # Adjustable range [3, 5], early stopping rounds, stops training when there's no improvement in validation loss for 3/5 rounds, used to prevent over-fitting
            reg: 0.001    # Adjustable range [0.0005, 0.001, 0.005, 0.01], regularization weight, used to prevent over-fitting
            n_epochs: 100 # Number of training epochs, generally not adjusted since most cases will trigger early stopping
    dataset:
        class: TSDatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2014-12-31]
                valid: [2015-01-01, 2016-12-31]
                test: [2017-01-01, 2020-08-01]
            step_len: 20
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
